spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DB}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true